# Site settings
title: NOVA Santé Intégrée
email: sarah.dionne@novasante.ch
description: > # ignore newlines
  Redirection to main website

theme: jekyll-theme-minimal

gems:
  - jekyll-redirect-from
