# Site settings
title: NOVA Santé Intégrée
email: sarah.dionne@novasante.ch
description: > # ignore newlines
  Redirection to main website
# logo: /assets/img/logo.png

theme: jekyll-theme-minimal

gems:
  - jekyll-redirect-from
